[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rhdh-rag-content"
description = "RAG for RHDH"
version = "0.2.0"
dependencies = [
    "lightspeed-rag-content @ git+https://github.com/lightspeed-core/rag-content@d90df77e415eae8575621cec23fa919a5c99a197",
    "pyyaml",
]

authors = [
    {name = "Maysun J Faisal"},
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "Apache"}
