[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rhdh-rag-content"
description = "RAG for RHDH"
version = "0.3.0"
dependencies = [
    "lightspeed-rag-content @ git+https://github.com/lightspeed-core/rag-content@6b927db8c33a6f0af073712d9893391e3d9c76d4",
    "pyyaml",
]

authors = [
    {name = "Maysun J Faisal"},
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "Apache"}
