#
#
# Copyright Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Build and Push RAG Container

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of RHDH documentation you want to build for. E.g. ('1.7')."
        required: true
      compute_flavor:
        description: "The compute flavor for the container build."
        required: false
        default: "cpu"
        type: choice
        options:
          - cpu
          - gpu
      experimental:
        description: "Build experimental version that will not override stable image tags."
        required: false
        default: false
        type: boolean

env:
  IMAGE_NAME: rag-content
  IMAGE_REGISTRY: quay.io
  REGISTRY_ORG: redhat-ai-dev
  CONTAINER_FILE: Containerfile

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.set_tag.outputs.latest_tag }}
    steps:
      - name: Set tag prefix
        id: set_tag
        run: |
          if [ "${{ inputs.experimental }}" == "true" ]; then
            echo "latest_tag=experimental-release-${{ inputs.version }}-lcs" >> $GITHUB_OUTPUT
          else
            echo "latest_tag=release-${{ inputs.version }}-lcs" >> $GITHUB_OUTPUT
          fi

  build:
    needs: setup
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set tag from setup
        run: |
          echo "LATEST_TAG=${{ needs.setup.outputs.latest_tag }}" >> $GITHUB_ENV
      - name: Install buildah
        run: |
          sudo apt update
          sudo apt install -y buildah
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build image with Buildah
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.LATEST_TAG }}-${{ matrix.arch }}-${{ github.sha }}
          containerfiles: |
            ${{ env.CONTAINER_FILE }}
          archs: ${{ matrix.arch }}
          oci: true
          build-args: |
            RHDH_DOCS_VERSION=${{ inputs.version }}
            FLAVOR=${{ inputs.compute_flavor }}
      - name: Check images
        run: |
          buildah images | grep '${{ env.IMAGE_NAME }}'
          echo '${{ steps.build_image.outputs.image }}'
          echo '${{ steps.build_image.outputs.tags }}'
      - name: Push architecture-specific image to Quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_ORG }}
          username: ${{ secrets.QUAY_REGISTRY_USERNAME }}
          password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}

  create-manifest:
    needs: [build, setup]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set tag from setup
        run: |
          echo "LATEST_TAG=${{ needs.setup.outputs.latest_tag }}" >> $GITHUB_ENV
      - name: Install buildah
        run: |
          sudo apt update
          sudo apt install -y buildah
      - name: Login to registry
        run: |
          echo "${{ secrets.QUAY_REGISTRY_PASSWORD }}" | buildah login --username "${{ secrets.QUAY_REGISTRY_USERNAME }}" --password-stdin ${{ env.IMAGE_REGISTRY }}
      - name: Create and push manifest
        run: |
          # Create manifests
          buildah manifest create ${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}
          buildah manifest add ${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }} ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}-amd64-${{ github.sha }}
          buildah manifest add ${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }} ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}-arm64-${{ github.sha }}
          
          buildah manifest create ${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}-${{ github.sha }}
          buildah manifest add ${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}-${{ github.sha }} ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}-amd64-${{ github.sha }}
          buildah manifest add ${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}-${{ github.sha }} ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}-arm64-${{ github.sha }}
          
          # Push manifests
          buildah manifest push --all ${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }} docker://${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}
          buildah manifest push --all ${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}-${{ github.sha }} docker://${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_ORG }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}-${{ github.sha }}